### ISSUE TITLE
Error while generating server stub

### ISSUE THREAD

**Issue by hiveship** [hevayo/swagger2cxf-maven-plugin#6]
I am trying to generate a CXF Server stub from a Swagger 2.0 Spec. I am getting an error during the Maven Build. 

Stack trace is:

```
writing file C:\Users\mnantel\workspace\swagger2cxf\src/gen\java/swagger2cxf\DefaultApiService.java
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.273 s
[INFO] Finished at: 2016-01-12T14:00:16+01:00
[INFO] Final Memory: 15M/219M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wso2.maven.plugins:swagger2cxf-maven-plugin:1.0-SNAPSHOT:generate (default-cli) on project swagger2cxf: Execution default-cli of goal org.wso2.maven.plugins:swagger2cxf-maven-plugin:1.0-SNAPSHOT:generate failed: Could not generate api file for '': Unexpected internal error near index 1
[ERROR] \
[ERROR] ^
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wso2.maven.plugins:swagger2cxf-maven-plugin:1.0-SNAPSHOT:generate (default-cli) on project swagger2cxf: Execution default-cli of goal org.wso2.maven.plugins:swagger2cxf-maven-plugin:1.0-SNAPSHOT:generate failed: Could not generate api file for ''
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.wso2.maven.plugins:swagger2cxf-maven-plugin:1.0-SNAPSHOT:generate failed: Could not generate api file for ''
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 20 more
Caused by: java.lang.RuntimeException: Could not generate api file for ''
    at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:296)
    at org.wso2.maven.plugins.APIGenMojo.execute(APIGenMojo.java:84)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ... 21 more
Caused by: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
    at java.util.regex.Pattern.error(Pattern.java:1924)
    at java.util.regex.Pattern.compile(Pattern.java:1671)
    at java.util.regex.Pattern.<init>(Pattern.java:1337)
    at java.util.regex.Pattern.compile(Pattern.java:1022)
    at java.lang.String.split(String.java:2313)
    at java.lang.String.split(String.java:2355)
    at org.wso2.maven.plugins.CxfCodeGen.apiFilename(CxfCodeGen.java:69)
    at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:275)
    ... 23 more
```

Attachment: my Swagger YAML file
[api.txt](https://github.com/hevayo/swagger2cxf-maven-plugin/files/87287/api.txt)

i also tried with the latest version of the Swagger Codegen Project (I updated the pom.xml file of the Swagger2CXF plugin from 2.1.4 to 2.1.5. After a rebuild of the plugin, I tried but now, Maven seems to not be able to load the plugin and I can't find why :/ 
Stack trace is:

```
reading from C:\Users\mnantel\workspace\swagger2cxf/src/main/resources/api.yaml
java.io.FileNotFoundException: JavaJaxRS\jersey1_18\dto.mustache (Le chemin d’accès spécifié est introuvable)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at io.swagger.codegen.AbstractGenerator.getTemplateReader(AbstractGenerator.java:51)
    at io.swagger.codegen.AbstractGenerator.readTemplate(AbstractGenerator.java:35)
    at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:201)
    at org.wso2.maven.plugins.APIGenMojo.execute(APIGenMojo.java:85)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
java.lang.RuntimeException: can't load template JavaJaxRS\jersey1_18\dto.mustache
    at io.swagger.codegen.AbstractGenerator.getTemplateReader(AbstractGenerator.java:60)
    at io.swagger.codegen.AbstractGenerator.readTemplate(AbstractGenerator.java:35)
    at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:201)
    at org.wso2.maven.plugins.APIGenMojo.execute(APIGenMojo.java:85)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

There is the same error while using the default Swagger petstore example.

**Comment by murthy5** [comment]
@hiveship did you ever resolve the initial error you had... 

Failed to execute goal org.wso2.maven.plugins:swagger2cxf-maven-plugin:1.0-SNAPSHOT:generate (default-cli) on project swagger2cxf: Execution default-cli of goal org.wso2.maven.plugins:swagger2cxf-maven-plugin:1.0-SNAPSHOT:generate failed: Could not generate api file for '': Unexpected internal error near index 1
[ERROR] \

I am running into the same issue right now.
